### PR TITLE
add additional packages

### PR DESCRIPTION
**Pull request by PatrikKopkan**
fix buildscript
- spec didn't contain debug info

fix not failing ci

better output of ci

### CODE REVIEW

**Comment by frenzymadness** [comment]
Could you please investigate the error in the CI?

**Comment by PatrikKopkan** [comment]
ok, now it should work. It passes when should and also fails. May I reset head to previous commit and merge it?

**Comment by frenzymadness** [comment]
I'd prefer to add packages to CI only when it pass with them. Otherwise our CI will always fail and you'll have to investigate all the time whether it's expected or not. Can we remove failing packages or update the tool to make the CI pass?

Let mw know if you want to discuss this further.

**Comment by PatrikKopkan** [comment]
Sure but for review I thought it would be good to see that when ci fails. I thought I tested previously but the ci failed only when last thing failed.

**Comment by frenzymadness** [comment]
One last thing. Would it be possible to split this change into two commits? In the first one, there might be described fixes for build script and the second one can contain only new packages. Currently, there are multiple changes in one commit and the topic of the commit says just "add additional packages".

**Comment by frenzymadness** [comment]
I'm gonna archive this project, take a look at https://github.com/befeleme/pyp2spec

**Pull request closed without merging**
